# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7204ff106e296c9e64d6bc96eabb787bb30c17b9309eec205a493972ce0647c04099cfc975622297459941460d34da17d51b635f5ab1fcbb7500fa920d8b6d3b

test:
  secret_key_base: ed2e933935b610b86fb6b50afe21c01df005781bbeb32a5ff6b861d167b768c11057eeecbffa28bb14f91db179485ecd46afb9a0b8c430c81fdd45234e823397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
